### ISSUE TITLE
In frontend, move call to supertokens.init in index.tsx

### ISSUE THREAD

**Issue by rishabhpoddar** [tyaga001/SuperTokens-Hasura-Demo#4]
We want to make sure that supertokens.init is the first thing we do in the app.

**Comment by tyaga001** [comment]
Moved to index.tsx

**Comment by rishabhpoddar** [comment]
It's still in here: https://github.com/tyaga001/SuperTokens-Hasura-Demo/blob/main/src/app-login/Login.tsx

**Comment by rishabhpoddar** [comment]
I see it in index.tsx now. I think you didn't remove the old login.tsx file.
