### ISSUE TITLE
In frontend, why are we redirecting to /auth in getRedirectionURL?

### ISSUE THREAD

**Issue by rishabhpoddar** [tyaga001/SuperTokens-Hasura-Demo#5]
If `context.action === 'SUCCESS'` is false, why are we sending to /auth?

**Comment by tyaga001** [comment]
changed to return undefined.

**Comment by rishabhpoddar** [comment]
Still returns /auth here: https://github.com/tyaga001/SuperTokens-Hasura-Demo/blob/main/src/app-login/Login.tsx

I think you must have not pushed the changes..

**Comment by rishabhpoddar** [comment]
I see it in index.tsx now. I think you didn't remove the old login.tsx file.
