### ISSUE TITLE
Bad naming of `Login` component on the frontend

### ISSUE THREAD

**Issue by rishabhpoddar** [tyaga001/SuperTokens-Hasura-Demo#8]
The login component in [this file](https://github.com/tyaga001/SuperTokens-Hasura-Demo/blob/main/src/app-login/Login.tsx), doesn't actually show the login UI. Instead, it's for showing the product listing which requires the user to be logged in.

So calling it Login is very confusing. In fact, having this component in a file called login is confusing.

**Comment by tyaga001** [comment]
Login component removed and now using like
 <Route
                    path="/"
                    element={
                        <EmailPassword.EmailPasswordAuth>
                            <RequireAuth>
                                <ProductList />
                            </RequireAuth>
                        </EmailPassword.EmailPasswordAuth>
                    }
                />

**Comment by rishabhpoddar** [comment]
I see. So you can remove the login component function from [this file](https://github.com/tyaga001/SuperTokens-Hasura-Demo/blob/main/src/app-login/Login.tsx)

**Comment by rishabhpoddar** [comment]
You can remove this file alltogether.

**Comment by tyaga001** [comment]
Removed
